### ISSUE TITLE
Setup mongoDB

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#19]
As a developer, we want to set up a database system on our server so we can the customer's data on our server. We will be using mongoDB to set up on our server and will be communicating with our nodeJS server.

**Comment by JPLanh** [comment]
Mongo server has been setted up, we need to test to make sure that a database can be created, and we can create a collection and data

**Comment by Aingty** [comment]
Created database but after server restart, the database disappeared. Currently testing this....

**Comment by Aingty** [comment]
It is fixed, databases will now remain even after server reboot.

**Comment by JPLanh** [comment]
I believe that would've been my fault because initally i started up the mongo server to another directory (our project directory/data). It seem apparent because that directory exist with few of the mongo stuff. After rebooting the server mongo started up with the default folder.
