### ISSUE TITLE
Setup connection between HTML and nodeJS

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#20]
As a developer, we would like to have a communication between HTML and our exprss' mongoDB server established and tested so we can execute post/get functions.

**Comment by hkellyanne** [comment]
Using a form to GET from the server. This form will send username field and password field after clicking  "Submit".

**Comment by JPLanh** [comment]
Tested and confirmed the communication has been establish and we were able to retrieve data from the mongo database
