### ISSUE TITLE
Establish a Java framework

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#22]

**Comment by PhuongHuynh96** [comment]
Began work on developing a JAVA framework using Javax.swing libraries (JPanel and JFrame). Still experimenting the library to find an easier way to implement the JAVA GUI

**Comment by JPLanh** [comment]
The size for this issue might be a bit bigger than it's declared. Issue has been broken down to smaller issues to make it more manageable. However continue familiarizing yourself with the Javax.swing library for now. Ideally with JPanel and JFrame, and how they are placed. Ideally we would like to place objects on the JPanel without any restriction of layouts.

**Comment by JPLanh** [comment]
Close this Issue once you've uploaded your working portion on github and comment with what you did.

**Comment by JPLanh** [comment]
The sub issue of these has been resolved. closing this now
