### ISSUE TITLE
Create mock DB query

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#24]
As a developer we would like to create a few test cases so we would be able to determine that the communication between our frontend and backend are working properly.

**Comment by Aingty** [comment]
Using the following sql statement, we can achieve this.
//SELECT * FROM users;
//INSERT INTO users ( userUID, userNAme, password, firstName, lastName, email, phone, dateOfBirth ) VALUES ( //Insert values here )
//DELETE FROM users WHERE UserUID='//userUID here'
//UPDATE users SET firstName="//set first name" WHERE UserUID="//UserUID here"

**Comment by Aingty** [comment]
I've created some more tables based off the "List of Attributes" documentation. Expect them to be populated into the database sometime later. Once finished, I will ask for a review of the tables.

**Comment by JPLanh** [comment]
Those are good for now, feel free to add any extra in this comments. The following sql statement was translated into express and works. Feel free to close this issue.

**Comment by Aingty** [comment]
Also, this issue is for "Testing" so I've created testing tables onto the MongoDB and left it there for further testing, if needed.

**Comment by JPLanh** [comment]
Code is working, be sure to close this when you can.
The testing is a separate issue, this issue is for creating the mock DB queries.
