### ISSUE TITLE
Establish a User Database

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#27]
As a developer, I would like to make a connection to the user database on MongoDB so I can store and retrieve users data.

**Comment by JPLanh** [comment]
I've overlooked this, upon finishing my issue for Establish an express model for users, it generated the table (or collection in mongoDB term) for the users automatically. @Aingty, can you check to confirm that the user table has the same variable as the List of attributes document?

**Comment by Aingty** [comment]
Yes, I checked and the attributes are all the same. However I am not sure as to what the "ISODate.." is. I am not sure if that is part of the collection. But every attribute from the document is present.

**Comment by Aingty** [comment]
@JPLanh , is it possible for you to insert to the user table again? I dropped the table and re created with standard naming for all of our tables (collections). We can discuss this during our next scrum as well. The name for the table is now called "User".
