### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#3]
Reference to the artifacts, please do purpose, goal and synopsis. If you'd like, you can tackle scope of the system, and objective.

**Comment by PhuongHuynh96** [comment]
I have written the purpose, goal, and synopsis within the google doc. I am unsure how to format the introduction, so you can format however you like.

**Comment by PhuongHuynh96** [comment]
system scope and objectives written in document,  please check to confirm
