### ISSUE TITLE
(HTML) Establish Sign-up communication

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/Food_Adventure_co.#40]
As a developer, I would like the user to be able to send their data so they can create a new user account.

**Comment by Aingty** [comment]
This issue has been resolved. I had to follow this link for helps with post-get request handling in js. 
Link : https://www.hacksparrow.com/post-get-request-handling-in-node-js-express.html?fbclid=IwAR1Oh3tb5wAwkDrYVzWNI9n-fv3jjcDQA-POgAp5ei71B30-qPGHi2G4uUc
